onerror {resume}
quietly virtual signal -install /eda_regional_max_tb/eda_regional_max_inst/eda_img_ram { /eda_regional_max_tb/eda_regional_max_inst/eda_img_ram/center_addr[5:3]} center_addr_row
quietly virtual signal -install /eda_regional_max_tb/eda_regional_max_inst/eda_img_ram { /eda_regional_max_tb/eda_regional_max_inst/eda_img_ram/center_addr[2:0]} center_addr_col
quietly virtual signal -install /eda_regional_max_tb/eda_regional_max_inst/eda_iterated_ram { /eda_regional_max_tb/eda_regional_max_inst/eda_iterated_ram/downright_addr[5:3]} row
quietly virtual signal -install /eda_regional_max_tb/eda_regional_max_inst/eda_iterated_ram { /eda_regional_max_tb/eda_regional_max_inst/eda_iterated_ram/downright_addr[2:0]} col
quietly virtual signal -install /eda_regional_max_tb/eda_regional_max_inst/eda_img_ram { /eda_regional_max_tb/eda_regional_max_inst/eda_img_ram/center_addr[7:4]} row
quietly virtual signal -install /eda_regional_max_tb/eda_regional_max_inst/eda_img_ram { /eda_regional_max_tb/eda_regional_max_inst/eda_img_ram/center_addr[3:0]} col
quietly WaveActivateNextPane {} 0
add wave -noupdate -radix binary /eda_regional_max_tb/eda_regional_max_inst/clk
add wave -noupdate -radix binary /eda_regional_max_tb/eda_regional_max_inst/reset_n
add wave -noupdate -radix binary /eda_regional_max_tb/eda_regional_max_inst/start
add wave -noupdate /eda_regional_max_tb/eda_regional_max_inst/pixel_in
add wave -noupdate -radix hexadecimal -childformat {{{/eda_regional_max_tb/eda_regional_max_inst/wr_addr[7]} -radix binary} {{/eda_regional_max_tb/eda_regional_max_inst/wr_addr[6]} -radix binary} {{/eda_regional_max_tb/eda_regional_max_inst/wr_addr[5]} -radix binary} {{/eda_regional_max_tb/eda_regional_max_inst/wr_addr[4]} -radix binary} {{/eda_regional_max_tb/eda_regional_max_inst/wr_addr[3]} -radix binary} {{/eda_regional_max_tb/eda_regional_max_inst/wr_addr[2]} -radix binary} {{/eda_regional_max_tb/eda_regional_max_inst/wr_addr[1]} -radix binary} {{/eda_regional_max_tb/eda_regional_max_inst/wr_addr[0]} -radix binary}} -subitemconfig {{/eda_regional_max_tb/eda_regional_max_inst/wr_addr[7]} {-radix binary} {/eda_regional_max_tb/eda_regional_max_inst/wr_addr[6]} {-radix binary} {/eda_regional_max_tb/eda_regional_max_inst/wr_addr[5]} {-radix binary} {/eda_regional_max_tb/eda_regional_max_inst/wr_addr[4]} {-radix binary} {/eda_regional_max_tb/eda_regional_max_inst/wr_addr[3]} {-radix binary} {/eda_regional_max_tb/eda_regional_max_inst/wr_addr[2]} {-radix binary} {/eda_regional_max_tb/eda_regional_max_inst/wr_addr[1]} {-radix binary} {/eda_regional_max_tb/eda_regional_max_inst/wr_addr[0]} {-radix binary}} /eda_regional_max_tb/eda_regional_max_inst/wr_addr
add wave -noupdate -radix binary /eda_regional_max_tb/eda_regional_max_inst/write_en
add wave -noupdate -radix binary /eda_regional_max_tb/eda_regional_max_inst/done
add wave -noupdate /eda_regional_max_tb/eda_regional_max_inst/wr_addr
add wave -noupdate /eda_regional_max_tb/eda_regional_max_inst/write_en
add wave -noupdate -radix binary -childformat {{{/eda_regional_max_tb/eda_regional_max_inst/matrix_output[9]} -radix binary} {{/eda_regional_max_tb/eda_regional_max_inst/matrix_output[8]} -radix binary} {{/eda_regional_max_tb/eda_regional_max_inst/matrix_output[7]} -radix binary} {{/eda_regional_max_tb/eda_regional_max_inst/matrix_output[6]} -radix binary} {{/eda_regional_max_tb/eda_regional_max_inst/matrix_output[5]} -radix binary} {{/eda_regional_max_tb/eda_regional_max_inst/matrix_output[4]} -radix binary} {{/eda_regional_max_tb/eda_regional_max_inst/matrix_output[3]} -radix binary} {{/eda_regional_max_tb/eda_regional_max_inst/matrix_output[2]} -radix binary} {{/eda_regional_max_tb/eda_regional_max_inst/matrix_output[1]} -radix binary} {{/eda_regional_max_tb/eda_regional_max_inst/matrix_output[0]} -radix binary}} -expand -subitemconfig {{/eda_regional_max_tb/eda_regional_max_inst/matrix_output[9]} {-radix binary} {/eda_regional_max_tb/eda_regional_max_inst/matrix_output[8]} {-radix binary} {/eda_regional_max_tb/eda_regional_max_inst/matrix_output[7]} {-radix binary} {/eda_regional_max_tb/eda_regional_max_inst/matrix_output[6]} {-radix binary} {/eda_regional_max_tb/eda_regional_max_inst/matrix_output[5]} {-radix binary} {/eda_regional_max_tb/eda_regional_max_inst/matrix_output[4]} {-radix binary} {/eda_regional_max_tb/eda_regional_max_inst/matrix_output[3]} {-radix binary} {/eda_regional_max_tb/eda_regional_max_inst/matrix_output[2]} {-radix binary} {/eda_regional_max_tb/eda_regional_max_inst/matrix_output[1]} {-radix binary} {/eda_regional_max_tb/eda_regional_max_inst/matrix_output[0]} {-radix binary}} /eda_regional_max_tb/eda_regional_max_inst/matrix_output
add wave -noupdate -radix binary -childformat {{{/eda_regional_max_tb/eda_regional_max_inst/strb_value[9]} -radix binary} {{/eda_regional_max_tb/eda_regional_max_inst/strb_value[8]} -radix binary} {{/eda_regional_max_tb/eda_regional_max_inst/strb_value[7]} -radix binary} {{/eda_regional_max_tb/eda_regional_max_inst/strb_value[6]} -radix binary} {{/eda_regional_max_tb/eda_regional_max_inst/strb_value[5]} -radix binary} {{/eda_regional_max_tb/eda_regional_max_inst/strb_value[4]} -radix binary} {{/eda_regional_max_tb/eda_regional_max_inst/strb_value[3]} -radix binary} {{/eda_regional_max_tb/eda_regional_max_inst/strb_value[2]} -radix binary} {{/eda_regional_max_tb/eda_regional_max_inst/strb_value[1]} -radix binary} {{/eda_regional_max_tb/eda_regional_max_inst/strb_value[0]} -radix binary}} -expand -subitemconfig {{/eda_regional_max_tb/eda_regional_max_inst/strb_value[9]} {-radix binary} {/eda_regional_max_tb/eda_regional_max_inst/strb_value[8]} {-radix binary} {/eda_regional_max_tb/eda_regional_max_inst/strb_value[7]} {-radix binary} {/eda_regional_max_tb/eda_regional_max_inst/strb_value[6]} {-radix binary} {/eda_regional_max_tb/eda_regional_max_inst/strb_value[5]} {-radix binary} {/eda_regional_max_tb/eda_regional_max_inst/strb_value[4]} {-radix binary} {/eda_regional_max_tb/eda_regional_max_inst/strb_value[3]} {-radix binary} {/eda_regional_max_tb/eda_regional_max_inst/strb_value[2]} {-radix binary} {/eda_regional_max_tb/eda_regional_max_inst/strb_value[1]} {-radix binary} {/eda_regional_max_tb/eda_regional_max_inst/strb_value[0]} {-radix binary}} /eda_regional_max_tb/eda_regional_max_inst/strb_value
add wave -noupdate -radix binary -childformat {{{/eda_regional_max_tb/eda_regional_max_inst/eda_iterated_ram/iterated_memory[9]} -radix binary} {{/eda_regional_max_tb/eda_regional_max_inst/eda_iterated_ram/iterated_memory[8]} -radix binary} {{/eda_regional_max_tb/eda_regional_max_inst/eda_iterated_ram/iterated_memory[7]} -radix binary} {{/eda_regional_max_tb/eda_regional_max_inst/eda_iterated_ram/iterated_memory[6]} -radix binary} {{/eda_regional_max_tb/eda_regional_max_inst/eda_iterated_ram/iterated_memory[5]} -radix binary} {{/eda_regional_max_tb/eda_regional_max_inst/eda_iterated_ram/iterated_memory[4]} -radix binary} {{/eda_regional_max_tb/eda_regional_max_inst/eda_iterated_ram/iterated_memory[3]} -radix binary} {{/eda_regional_max_tb/eda_regional_max_inst/eda_iterated_ram/iterated_memory[2]} -radix binary} {{/eda_regional_max_tb/eda_regional_max_inst/eda_iterated_ram/iterated_memory[1]} -radix binary} {{/eda_regional_max_tb/eda_regional_max_inst/eda_iterated_ram/iterated_memory[0]} -radix binary}} -expand -subitemconfig {{/eda_regional_max_tb/eda_regional_max_inst/eda_iterated_ram/iterated_memory[9]} {-radix binary} {/eda_regional_max_tb/eda_regional_max_inst/eda_iterated_ram/iterated_memory[8]} {-radix binary} {/eda_regional_max_tb/eda_regional_max_inst/eda_iterated_ram/iterated_memory[7]} {-radix binary} {/eda_regional_max_tb/eda_regional_max_inst/eda_iterated_ram/iterated_memory[6]} {-radix binary} {/eda_regional_max_tb/eda_regional_max_inst/eda_iterated_ram/iterated_memory[5]} {-radix binary} {/eda_regional_max_tb/eda_regional_max_inst/eda_iterated_ram/iterated_memory[4]} {-radix binary} {/eda_regional_max_tb/eda_regional_max_inst/eda_iterated_ram/iterated_memory[3]} {-radix binary} {/eda_regional_max_tb/eda_regional_max_inst/eda_iterated_ram/iterated_memory[2]} {-radix binary} {/eda_regional_max_tb/eda_regional_max_inst/eda_iterated_ram/iterated_memory[1]} {-radix binary} {/eda_regional_max_tb/eda_regional_max_inst/eda_iterated_ram/iterated_memory[0]} {-radix binary}} /eda_regional_max_tb/eda_regional_max_inst/eda_iterated_ram/iterated_memory
TreeUpdate [SetDefaultTree]
WaveRestoreCursors {{Cursor 2} {17010000 ps} 0}
quietly wave cursor active 1
configure wave -namecolwidth 148
configure wave -valuecolwidth 100
configure wave -justifyvalue left
configure wave -signalnamewidth 1
configure wave -snapdistance 10
configure wave -datasetprefix 0
configure wave -rowmargin 4
configure wave -childrowmargin 2
configure wave -gridoffset 0
configure wave -gridperiod 1
configure wave -griddelta 40
configure wave -timeline 0
configure wave -timelineunits ns
update
WaveRestoreZoom {5064291 ps} {30385763 ps}
